name: Fix PHP code style issues

on:
  push:
    paths:
      - '**.php'

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: "Run formatter"
        uses: aglipanci/laravel-pint-action@2.6
        with:
          testMode: true
          useComposer: true
          parallel: true
